### ISSUE TITLE
Ngrok link not generating, it just leaves it blank 

### ISSUE THREAD

**Issue by alaw75** [x3rz/blackeye#1]

**Comment by j-dogcoder** [comment]
I get the same thing.

**Comment by DaShoe** [comment]
So do I

**Comment by x3rz** [comment]
this is tested on kali linux env also check if you have updated required services and its working fine also if you want to use it again then i prefer making new auth token from your ngrok account 
It shows the link.

**Comment by HHsenpai-spec** [comment]
![image](https://user-images.githubusercontent.com/73730929/97837769-ddf2d900-1d19-11eb-99a5-fea22551c270.png)
still bot fixed

**Comment by Mrzeens** [comment]
i tried to make fresh auth tokens but that hasnt helped at all it still doesnt generate a link for me...any advice bro...

**Comment by j-dogcoder** [comment]
Still not working for me either

**Comment by j-dogcoder** [comment]
I'm not using Kali though.

**Comment by alaw75** [comment]
Tried it with kali linux and works fine. I guess it just doesn't work on other OS than kali

**Comment by j-dogcoder** [comment]
I just tried with a fresh version of kali. No link for me.

**Comment by j-dogcoder** [comment]
@alaw75 Do I have to put in a rock token before getting a link?

**Comment by DaShoe** [comment]
Try reinstalling / enabling the lamp stack

**Comment by j-dogcoder** [comment]
@DaShoe How do you do that?

**Comment by j-dogcoder** [comment]
Sort of off-topic, but I created a discord for Red Teamers and Coders if anyone wants to join.
The server is very much still In a development phase so if you join you can help build it out. If you do help, you get Admin status.
[Join the Server here](https://discord.gg/SmJdhqHy)

**Comment by j-dogcoder** [comment]
I think we may have fixed things in issue #2. 

```
I have found a way to get this work if you are using an arm processor

Open the blackeye folder and remove the ngrok file
Just go to ngrok.com and download the file according to your processor and move it to the blackeye folder and unzip it. Now add your authtoken you found from ngrok. 
Now you can run the script again. It should work for you now.

_Originally posted by @LAKSHAY184 in https://github.com/x3rz/blackeye/issues/2#issuecomment-721219581_
```

**Comment by alaw75** [comment]
> @alaw75 Do I have to put in a rock token before getting a link?

Yeah gave rock token before the link

**Comment by alaw75** [comment]
Also I re installed ngrok

**Comment by phisher6969** [comment]
it works just fine on kali

**Comment by j-dogcoder** [comment]
Yep. Still broken

**Comment by caseyaphil** [comment]
This is a bug with v1.5 that I found out the hard way. Took me three days to find out. Delete v1.5 and stick with v1.1. its working fine there

**Comment by asdfghjA1** [comment]
This works properly only in KALI LINUS so if any of you are not using linus or its distributons u will be facing all the issues :0 ........i tried with all the popular OS ....... Linux (Specifically KALI ) works the best

**Comment by peebowo** [comment]
list of commands to make ngrok work
wget "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip" -P /your_path/blackeye
./ngrok authtoken YOUR_AUTHENTICATION_TOKEN_IN_www.dashboard.ngrok.com/get-started/setup
./ngrok https 80 #THIS PART IS IMPORTANT FOR NGROK TO WORK
sudo reboot
./blackeye.sh
check if this works for you guys, it did for me!

**Comment by Samyan1Sharma** [comment]
> Sort of off-topic, but I created a discord for Red Teamers and Coders if anyone wants to join.
> The server is very much still In a development phase so if you join you can help build it out. If you do help, you get Admin status.
> [Join the Server here](https://discord.gg/SmJdhqHy)

Link expired

**Comment by Samyan1Sharma** [comment]
> list of commands to make ngrok work
> wget "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip" -P /your_path/blackeye
> ./ngrok authtoken YOUR_AUTHENTICATION_TOKEN_IN_[www.dashboard.ngrok.com/get-started/setup](http://www.dashboard.ngrok.com/get-started/setup)
> ./ngrok http 80 #THIS PART IS IMPORTANT FOR NGROK TO WORK
> sudo reboot
> ./blackeye.sh
> check if this works for you guys, it did for me!

That link expired

**Comment by j-dogcoder** [comment]
@Samyan1Sharma I can add a new link for the discord if you're interested.

**Comment by Samyan1Sharma** [comment]
> @Samyan1Sharma I can add a new link for the discord if you're interested.

Send it

**Comment by j-dogcoder** [comment]
@Samyan1Sharma 

[https://discord.gg/xfASWfu5DB](https://discord.gg/xfASWfu5DB)

**Comment by j-dogcoder** [comment]
Is this good to be closed @alaw75?

**Comment by hamzahmhmmd** [comment]
this 3 step working for me (wsl kali linux)
1. start blackeye.sh file
2. wait until "Waiting victim open the link..." show up
3. go to [https://dashboard.ngrok.com/status/tunnels](https://dashboard.ngrok.com/status/tunnels) to check your generated link

**Comment by n1c0t1n3** [comment]
> this 3 step working for me (wsl kali linux)
> 
>     1. start blackeye.sh file
> 
>     2. wait until "Waiting victim open the link..." show up
> 
>     3. go to https://dashboard.ngrok.com/status/tunnels to check your generated link

I tried it. Yes, it worked! Such a simple method lol.

**Comment by harrytheman12** [comment]
that doesnt work for me

**Comment by ciastron** [comment]
It doesn't work for me. The problem is that blackeye.sh does this command to get the link
`link=$(curl -s -N http://127.0.0.1:4040/status | grep -o "https://dashboard.ngrok.com/status/tunnels") #line 436` 
Unfortunately the link you want to get is loaded in http://127.0.0.1:4040/status with a javascript so that previous command doesn't see the phishing link.
To actually get it, you can manually go on http:127.0.0.1:4040/status or on link https://dashboard.ngrok.com/status/tunnels

**Comment by harrytheman12** [comment]
this doesnt work? it says no tunnels

Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by powersem2007** [comment]
> I think we may have fixed things in issue #2.
> 
> ```
> I have found a way to get this work if you are using an arm processor
> 
> Open the blackeye folder and remove the ngrok file
> Just go to ngrok.com and download the file according to your processor and move it to the blackeye folder and unzip it. Now add your authtoken you found from ngrok. 
> Now you can run the script again. It should work for you now.
> 
> _Originally posted by @LAKSHAY184 in https://github.com/x3rz/blackeye/issues/2#issuecomment-721219581_
> ```

but where is the blackeye folder

**Comment by rinkimekari** [comment]
> It doesn't work for me. The problem is that blackeye.sh does this command to get the link
> `link=$(curl -s -N http://127.0.0.1:4040/status | grep -o "https://dashboard.ngrok.com/status/tunnels") #line 436`
> Unfortunately the link you want to get is loaded in http://127.0.0.1:4040/status with a javascript so that previous command doesn't see the phishing link.
> To actually get it, you can manually go on http:127.0.0.1:4040/status or on link https://dashboard.ngrok.com/status/tunnels

i can get the link this way, but when i enter anything in the login field to test it and press log in, it doesnt send the info to my terminal at all so i have no way of seeing what the victim enters in

**Comment by CxllZ** [comment]
what i did was install the ngrok zip file and move to the black eye folder
then unzip the ngrok.zip file, open terminal and paste ur ngrok auth token
now run ./blackeye.sh and generate a web link
finally go into https://dashboard.ngrok.com/status/tunnels and u will see ur ngrok links!

**Comment by scorpion-0** [comment]
> I'm not using Kali though.

I dont think its working on anything but Kali.

**Comment by allamvignesh** [comment]
Ok this is weird ☺️ it works on parrot security but not on kali for me.

**Comment by IndianCodr** [comment]
> Tried it with kali linux and works fine. I guess it just doesn't work on other OS than kali

It workds on Parrot and Ubuntu too, but I tried to run it on termux but there it doesn't shows the link.
