### ISSUE TITLE
Facebook Fix 

### ISSUE THREAD

**Issue by HHsenpai-spec** [x3rz/blackeye#3]
![image](https://user-images.githubusercontent.com/73730929/97857800-384f6200-1d39-11eb-8efb-41fb4a02f715.png)

**Comment by TheRevenge** [comment]
Yeah, the tool should be updated so it downloads the assets because now, facebook, github... are blocking remote access to their assets (Cross-Origin Request Blocked).

**Comment by j-dogcoder** [comment]
I don’t know how active the owner is so you may want to fork this and try to fix it on your own. I have contacted the owner about looking at this project and if I don't hear back I may create a fork that you all are welcome to come and edit. I will keep everyone posted.

**Comment by TheRevenge** [comment]
Honestly, you shouldn't wait for him giving an answer.

**Comment by x3rz** [comment]
i understand but currently, i am busy with some more important projects  also if you make PR instead of taking negative would be best

**Comment by j-dogcoder** [comment]
I have created a fork to work on. Everyone is welcome. You can find it at [https://github.com/j-dogcoder/Blackeye-2.0](https://github.com/j-dogcoder/Blackeye-2.0)

**Comment by j-dogcoder** [comment]
@TheRevenge @HHsenpai-spec The fork has a developer who just finished up a new version of Facebook. The commit should be coming in soon so we will have a working Facebook up soon.
